[alias]
dev = "run --package ruff_dev --bin ruff_dev"
benchmark = "bench -p ruff_benchmark --bench linter --bench formatter --"

# statically link the C runtime so the executable does not depend on
# that shared/dynamic library.
#
# See: https://github.com/astral-sh/ruff/issues/11503
[target.'cfg(all(target_env="msvc", target_os = "windows"))']
rustflags = ["-C", "target-feature=+crt-static"]

# Pexip Vendored updates
[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/MichaReiser/salsa.git?tag=red-knot-0.0.1"]
git = "https://github.com/MichaReiser/salsa.git"
tag = "red-knot-0.0.1"
replace-with = "vendored-sources"

[source."git+https://github.com/astral-sh/lsp-types.git?rev=3512a9f"]
git = "https://github.com/astral-sh/lsp-types.git"
rev = "3512a9f"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"

